/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as CustomerPaymentRouteImport } from './routes/customer.payment'
import { Route as CustomerMenuRouteImport } from './routes/customer.menu'
import { Route as CustomerCheckoutRouteImport } from './routes/customer.checkout'
import { Route as CustomerCartRouteImport } from './routes/customer.cart'
import { Route as AppThemeRouteImport } from './routes/app.theme'
import { Route as AppTablesRouteImport } from './routes/app.tables'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRoomsRouteImport } from './routes/app.rooms'
import { Route as AppQrManagementRouteImport } from './routes/app.qr-management'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPreviewRouteImport } from './routes/app.preview'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppMenuRouteImport } from './routes/app.menu'
import { Route as AppKitchenRouteImport } from './routes/app.kitchen'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as CustomerPaymentSuccessRouteImport } from './routes/customer.payment.success'
import { Route as CustomerPaymentFailedRouteImport } from './routes/customer.payment.failed'
import { Route as CustomerOrderTrackingIdRouteImport } from './routes/customer.order-tracking.$id'
import { Route as CustomerOrderConfirmationIdRouteImport } from './routes/customer.order-confirmation.$id'
import { Route as CustomerMenuItemIdRouteImport } from './routes/customer.menu.item.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const CustomerPaymentRoute = CustomerPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerMenuRoute = CustomerMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCheckoutRoute = CustomerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CustomerRoute,
} as any)
const AppThemeRoute = AppThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AppRoute,
} as any)
const AppTablesRoute = AppTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppQrManagementRoute = AppQrManagementRouteImport.update({
  id: '/qr-management',
  path: '/qr-management',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPreviewRoute = AppPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppKitchenRoute = AppKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const CustomerPaymentSuccessRoute = CustomerPaymentSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CustomerPaymentRoute,
} as any)
const CustomerPaymentFailedRoute = CustomerPaymentFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => CustomerPaymentRoute,
} as any)
const CustomerOrderTrackingIdRoute = CustomerOrderTrackingIdRouteImport.update({
  id: '/order-tracking/$id',
  path: '/order-tracking/$id',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrderConfirmationIdRoute =
  CustomerOrderConfirmationIdRouteImport.update({
    id: '/order-confirmation/$id',
    path: '/order-confirmation/$id',
    getParentRoute: () => CustomerRoute,
  } as any)
const CustomerMenuItemIdRoute = CustomerMenuItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => CustomerMenuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/menu': typeof AppMenuRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/preview': typeof AppPreviewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/qr-management': typeof AppQrManagementRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/tables': typeof AppTablesRoute
  '/app/theme': typeof AppThemeRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/menu': typeof CustomerMenuRouteWithChildren
  '/customer/payment': typeof CustomerPaymentRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/customer/order-confirmation/$id': typeof CustomerOrderConfirmationIdRoute
  '/customer/order-tracking/$id': typeof CustomerOrderTrackingIdRoute
  '/customer/payment/failed': typeof CustomerPaymentFailedRoute
  '/customer/payment/success': typeof CustomerPaymentSuccessRoute
  '/customer/menu/item/$id': typeof CustomerMenuItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/menu': typeof AppMenuRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/preview': typeof AppPreviewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/qr-management': typeof AppQrManagementRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/tables': typeof AppTablesRoute
  '/app/theme': typeof AppThemeRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/menu': typeof CustomerMenuRouteWithChildren
  '/customer/payment': typeof CustomerPaymentRouteWithChildren
  '/app': typeof AppIndexRoute
  '/customer/order-confirmation/$id': typeof CustomerOrderConfirmationIdRoute
  '/customer/order-tracking/$id': typeof CustomerOrderTrackingIdRoute
  '/customer/payment/failed': typeof CustomerPaymentFailedRoute
  '/customer/payment/success': typeof CustomerPaymentSuccessRoute
  '/customer/menu/item/$id': typeof CustomerMenuItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/menu': typeof AppMenuRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/preview': typeof AppPreviewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/qr-management': typeof AppQrManagementRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/tables': typeof AppTablesRoute
  '/app/theme': typeof AppThemeRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/menu': typeof CustomerMenuRouteWithChildren
  '/customer/payment': typeof CustomerPaymentRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/customer/order-confirmation/$id': typeof CustomerOrderConfirmationIdRoute
  '/customer/order-tracking/$id': typeof CustomerOrderTrackingIdRoute
  '/customer/payment/failed': typeof CustomerPaymentFailedRoute
  '/customer/payment/success': typeof CustomerPaymentSuccessRoute
  '/customer/menu/item/$id': typeof CustomerMenuItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/customer'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/app/analytics'
    | '/app/kitchen'
    | '/app/menu'
    | '/app/orders'
    | '/app/preview'
    | '/app/profile'
    | '/app/qr-management'
    | '/app/rooms'
    | '/app/settings'
    | '/app/subscription'
    | '/app/tables'
    | '/app/theme'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/menu'
    | '/customer/payment'
    | '/app/'
    | '/customer/order-confirmation/$id'
    | '/customer/order-tracking/$id'
    | '/customer/payment/failed'
    | '/customer/payment/success'
    | '/customer/menu/item/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/app/analytics'
    | '/app/kitchen'
    | '/app/menu'
    | '/app/orders'
    | '/app/preview'
    | '/app/profile'
    | '/app/qr-management'
    | '/app/rooms'
    | '/app/settings'
    | '/app/subscription'
    | '/app/tables'
    | '/app/theme'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/menu'
    | '/customer/payment'
    | '/app'
    | '/customer/order-confirmation/$id'
    | '/customer/order-tracking/$id'
    | '/customer/payment/failed'
    | '/customer/payment/success'
    | '/customer/menu/item/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/customer'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/app/analytics'
    | '/app/kitchen'
    | '/app/menu'
    | '/app/orders'
    | '/app/preview'
    | '/app/profile'
    | '/app/qr-management'
    | '/app/rooms'
    | '/app/settings'
    | '/app/subscription'
    | '/app/tables'
    | '/app/theme'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/menu'
    | '/customer/payment'
    | '/app/'
    | '/customer/order-confirmation/$id'
    | '/customer/order-tracking/$id'
    | '/customer/payment/failed'
    | '/customer/payment/success'
    | '/customer/menu/item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/customer/payment': {
      id: '/customer/payment'
      path: '/payment'
      fullPath: '/customer/payment'
      preLoaderRoute: typeof CustomerPaymentRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/menu': {
      id: '/customer/menu'
      path: '/menu'
      fullPath: '/customer/menu'
      preLoaderRoute: typeof CustomerMenuRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/checkout': {
      id: '/customer/checkout'
      path: '/checkout'
      fullPath: '/customer/checkout'
      preLoaderRoute: typeof CustomerCheckoutRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/cart': {
      id: '/customer/cart'
      path: '/cart'
      fullPath: '/customer/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/app/theme': {
      id: '/app/theme'
      path: '/theme'
      fullPath: '/app/theme'
      preLoaderRoute: typeof AppThemeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tables': {
      id: '/app/tables'
      path: '/tables'
      fullPath: '/app/tables'
      preLoaderRoute: typeof AppTablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rooms': {
      id: '/app/rooms'
      path: '/rooms'
      fullPath: '/app/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/qr-management': {
      id: '/app/qr-management'
      path: '/qr-management'
      fullPath: '/app/qr-management'
      preLoaderRoute: typeof AppQrManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/preview': {
      id: '/app/preview'
      path: '/preview'
      fullPath: '/app/preview'
      preLoaderRoute: typeof AppPreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/menu': {
      id: '/app/menu'
      path: '/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kitchen': {
      id: '/app/kitchen'
      path: '/kitchen'
      fullPath: '/app/kitchen'
      preLoaderRoute: typeof AppKitchenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/customer/payment/success': {
      id: '/customer/payment/success'
      path: '/success'
      fullPath: '/customer/payment/success'
      preLoaderRoute: typeof CustomerPaymentSuccessRouteImport
      parentRoute: typeof CustomerPaymentRoute
    }
    '/customer/payment/failed': {
      id: '/customer/payment/failed'
      path: '/failed'
      fullPath: '/customer/payment/failed'
      preLoaderRoute: typeof CustomerPaymentFailedRouteImport
      parentRoute: typeof CustomerPaymentRoute
    }
    '/customer/order-tracking/$id': {
      id: '/customer/order-tracking/$id'
      path: '/order-tracking/$id'
      fullPath: '/customer/order-tracking/$id'
      preLoaderRoute: typeof CustomerOrderTrackingIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/order-confirmation/$id': {
      id: '/customer/order-confirmation/$id'
      path: '/order-confirmation/$id'
      fullPath: '/customer/order-confirmation/$id'
      preLoaderRoute: typeof CustomerOrderConfirmationIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/menu/item/$id': {
      id: '/customer/menu/item/$id'
      path: '/item/$id'
      fullPath: '/customer/menu/item/$id'
      preLoaderRoute: typeof CustomerMenuItemIdRouteImport
      parentRoute: typeof CustomerMenuRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppKitchenRoute: typeof AppKitchenRoute
  AppMenuRoute: typeof AppMenuRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPreviewRoute: typeof AppPreviewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQrManagementRoute: typeof AppQrManagementRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppTablesRoute: typeof AppTablesRoute
  AppThemeRoute: typeof AppThemeRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppKitchenRoute: AppKitchenRoute,
  AppMenuRoute: AppMenuRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPreviewRoute: AppPreviewRoute,
  AppProfileRoute: AppProfileRoute,
  AppQrManagementRoute: AppQrManagementRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppTablesRoute: AppTablesRoute,
  AppThemeRoute: AppThemeRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CustomerMenuRouteChildren {
  CustomerMenuItemIdRoute: typeof CustomerMenuItemIdRoute
}

const CustomerMenuRouteChildren: CustomerMenuRouteChildren = {
  CustomerMenuItemIdRoute: CustomerMenuItemIdRoute,
}

const CustomerMenuRouteWithChildren = CustomerMenuRoute._addFileChildren(
  CustomerMenuRouteChildren,
)

interface CustomerPaymentRouteChildren {
  CustomerPaymentFailedRoute: typeof CustomerPaymentFailedRoute
  CustomerPaymentSuccessRoute: typeof CustomerPaymentSuccessRoute
}

const CustomerPaymentRouteChildren: CustomerPaymentRouteChildren = {
  CustomerPaymentFailedRoute: CustomerPaymentFailedRoute,
  CustomerPaymentSuccessRoute: CustomerPaymentSuccessRoute,
}

const CustomerPaymentRouteWithChildren = CustomerPaymentRoute._addFileChildren(
  CustomerPaymentRouteChildren,
)

interface CustomerRouteChildren {
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerCheckoutRoute: typeof CustomerCheckoutRoute
  CustomerMenuRoute: typeof CustomerMenuRouteWithChildren
  CustomerPaymentRoute: typeof CustomerPaymentRouteWithChildren
  CustomerOrderConfirmationIdRoute: typeof CustomerOrderConfirmationIdRoute
  CustomerOrderTrackingIdRoute: typeof CustomerOrderTrackingIdRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerCartRoute: CustomerCartRoute,
  CustomerCheckoutRoute: CustomerCheckoutRoute,
  CustomerMenuRoute: CustomerMenuRouteWithChildren,
  CustomerPaymentRoute: CustomerPaymentRouteWithChildren,
  CustomerOrderConfirmationIdRoute: CustomerOrderConfirmationIdRoute,
  CustomerOrderTrackingIdRoute: CustomerOrderTrackingIdRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
